#.travis.yml
language: ruby
rvm:
- 2.1

# branch whitelist
branches:
  only:
  - dev

before_script:
 - chmod +x cibuild.sh

script: ./cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer“
